# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot_comms.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'robot_comms.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11robot_comms.proto\x12\x05robot\"L\n\x16\x44ifferentialDriveState\x12\t\n\x01v\x18\x01 \x01(\x01\x12\r\n\x05omega\x18\x02 \x01(\x01\x12\x18\n\x10wheel_velocities\x18\x03 \x03(\x02\"5\n\tSpotState\x12\x13\n\x0b\x62ody_height\x18\x01 \x01(\x01\x12\x13\n\x0bis_standing\x18\x02 \x01(\x08\"\'\n\x0bMoveCommand\x12\t\n\x01v\x18\x01 \x01(\x01\x12\r\n\x05omega\x18\x02 \x01(\x01\"0\n\x08Register\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x12\n\nrobot_type\x18\x02 \x01(\t\"\xad\x01\n\x0bMeasurement\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\r\n\x05theta\x18\x03 \x01(\x01\x12\x39\n\x10\x64iff_drive_state\x18\n \x01(\x0b\x32\x1d.robot.DifferentialDriveStateH\x00\x12&\n\nspot_state\x18\x0b \x01(\x0b\x32\x10.robot.SpotStateH\x00\x42\x16\n\x14robot_specific_state\"k\n\x0e\x43lientToServer\x12#\n\x08register\x18\x01 \x01(\x0b\x32\x0f.robot.RegisterH\x00\x12)\n\x0bmeasurement\x18\x02 \x01(\x0b\x32\x12.robot.MeasurementH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'robot_comms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_DIFFERENTIALDRIVESTATE']._serialized_start = 28
    _globals['_DIFFERENTIALDRIVESTATE']._serialized_end = 104
    _globals['_SPOTSTATE']._serialized_start = 106
    _globals['_SPOTSTATE']._serialized_end = 159
    _globals['_MOVECOMMAND']._serialized_start = 161
    _globals['_MOVECOMMAND']._serialized_end = 200
    _globals['_REGISTER']._serialized_start = 202
    _globals['_REGISTER']._serialized_end = 250
    _globals['_MEASUREMENT']._serialized_start = 253
    _globals['_MEASUREMENT']._serialized_end = 426
    _globals['_CLIENTTOSERVER']._serialized_start = 428
    _globals['_CLIENTTOSERVER']._serialized_end = 535
# @@protoc_insertion_point(module_scope)
