name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Install dependencies + Shibuya theme
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install shibuya-sphinx-theme

      # 4. Build Sphinx docs
      - name: Build Docs
        run: sphinx-build -b html docs/source docs/build

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          clean: true
