name: Deploy Docs

on:
  push:
    branches:
      - main  # Run on pushes to main branch

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install sphinx sphinx_rtd_theme  # or Shibuya theme if needed

      # 4. Build the Sphinx docs
      - name: Build Sphinx Docs
        run: sphinx-build -b html docs/source docs/build

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          clean: true
